[package]
name = "portproxy"
version = "0.1.0-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros"] }
toml = "0.5"
derive-getters = "0.2"
log = "0.4"
env_logger = "0.9"
serde = { version = "1.0", features = ["derive"] }
futures = "0.3"
